//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA01A
    {
        public int BA01A_ID { get; set; }
        public string INC_NO { get; set; }
        public string INC_NM { get; set; }
        public string TEL_NO { get; set; }
        public string FAX_NO { get; set; }
        public string ADD_DR { get; set; }
        public Nullable<int> BA03A_ID { get; set; }
        public string BNK_I1 { get; set; }
        public string ACC_N1 { get; set; }
        public Nullable<int> PAY_DY { get; set; }
        public string EIN_NO { get; set; }
        public string REM_MM { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string SRT_NM { get; set; }
    }
}
