//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FN01
    {
        public int FN01_ID { get; set; }
        public Nullable<int> PAR_ID { get; set; }
        public string NAM_TW { get; set; }
        public string NAM_CN { get; set; }
        public string NAM_US { get; set; }
        public string NAM_VN { get; set; }
        public string ACT_RF { get; set; }
        public Nullable<int> ORD_NO { get; set; }
        public int VIS_TF { get; set; }
        public int ENB_TF { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
    }
}
