//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR01A
    {
        public int TR01A_ID { get; set; }
        public string PUR_NO { get; set; }
        public string PUR_DT { get; set; }
        public string EXP_DT { get; set; }
        public int BA01A_ID { get; set; }
        public int BA01B_ID { get; set; }
        public int BA03A_ID { get; set; }
        public Nullable<decimal> CUR_RT { get; set; }
        public Nullable<decimal> TOT_MY { get; set; }
        public string REM_MM { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER { get; set; }
        public string CPN_NM { get; set; }
        public string CFN_YN { get; set; }
        public string CFN_DT { get; set; }
        public string RCV_DT { get; set; }
        public string IVN_NO { get; set; }
        public Nullable<double> TAX_RT { get; set; }
        public string CFN_U1 { get; set; }
        public string CFN_U2 { get; set; }
    }
}
