//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 異常結案 的當地語系化字串。
        /// </summary>
        internal static string AbnormalConfirm {
            get {
                return ResourceManager.GetString("AbnormalConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實際到貨日期 的當地語系化字串。
        /// </summary>
        internal static string ActArriveDate {
            get {
                return ResourceManager.GetString("ActArriveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全數送達 的當地語系化字串。
        /// </summary>
        internal static string AllArrive {
            get {
                return ResourceManager.GetString("AllArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請結案 的當地語系化字串。
        /// </summary>
        internal static string ApplyConfirm {
            get {
                return ResourceManager.GetString("ApplyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請中 的當地語系化字串。
        /// </summary>
        internal static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請人 的當地語系化字串。
        /// </summary>
        internal static string ApplyUser {
            get {
                return ResourceManager.GetString("ApplyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到貨狀態 的當地語系化字串。
        /// </summary>
        internal static string ArriveStatus {
            get {
                return ResourceManager.GetString("ArriveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銀行名稱 的當地語系化字串。
        /// </summary>
        internal static string BA01A_ACC_N1 {
            get {
                return ResourceManager.GetString("BA01A_ACC_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        internal static string BA01A_ADD_DR {
            get {
                return ResourceManager.GetString("BA01A_ADD_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幣別 的當地語系化字串。
        /// </summary>
        internal static string BA01A_BA03A {
            get {
                return ResourceManager.GetString("BA01A_BA03A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 銀行帳號 的當地語系化字串。
        /// </summary>
        internal static string BA01A_BNK_I1 {
            get {
                return ResourceManager.GetString("BA01A_BNK_I1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 統一編號 的當地語系化字串。
        /// </summary>
        internal static string BA01A_EIN_NO {
            get {
                return ResourceManager.GetString("BA01A_EIN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳真 的當地語系化字串。
        /// </summary>
        internal static string BA01A_FAX_NO {
            get {
                return ResourceManager.GetString("BA01A_FAX_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商名稱 的當地語系化字串。
        /// </summary>
        internal static string BA01A_INC_NM {
            get {
                return ResourceManager.GetString("BA01A_INC_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商代號 的當地語系化字串。
        /// </summary>
        internal static string BA01A_INC_NO {
            get {
                return ResourceManager.GetString("BA01A_INC_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結帳天數 的當地語系化字串。
        /// </summary>
        internal static string BA01A_PAY_DY {
            get {
                return ResourceManager.GetString("BA01A_PAY_DY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商簡稱 的當地語系化字串。
        /// </summary>
        internal static string BA01A_SRT_NM {
            get {
                return ResourceManager.GetString("BA01A_SRT_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        internal static string BA01A_TEL_NO {
            get {
                return ResourceManager.GetString("BA01A_TEL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人 的當地語系化字串。
        /// </summary>
        internal static string BA01B_CNT_NM {
            get {
                return ResourceManager.GetString("BA01B_CNT_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子信箱 的當地語系化字串。
        /// </summary>
        internal static string BA01B_EML_DR {
            get {
                return ResourceManager.GetString("BA01B_EML_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分機 的當地語系化字串。
        /// </summary>
        internal static string BA01B_TEL_EX {
            get {
                return ResourceManager.GetString("BA01B_TEL_EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話專線 的當地語系化字串。
        /// </summary>
        internal static string BA01B_TEL_NO {
            get {
                return ResourceManager.GetString("BA01B_TEL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 英文名稱 的當地語系化字串。
        /// </summary>
        internal static string BA02A_ENG_NM {
            get {
                return ResourceManager.GetString("BA02A_ENG_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品名稱 的當地語系化字串。
        /// </summary>
        internal static string BA02A_ITM_NM {
            get {
                return ResourceManager.GetString("BA02A_ITM_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品代號 的當地語系化字串。
        /// </summary>
        internal static string BA02A_ITM_NO {
            get {
                return ResourceManager.GetString("BA02A_ITM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 商品規格 的當地語系化字串。
        /// </summary>
        internal static string BA02A_ITM_SP {
            get {
                return ResourceManager.GetString("BA02A_ITM_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        internal static string BA02A_UNT_NM {
            get {
                return ResourceManager.GetString("BA02A_UNT_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設價錢 的當地語系化字串。
        /// </summary>
        internal static string BA02B_PUR_PR {
            get {
                return ResourceManager.GetString("BA02B_PUR_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幣別代號 的當地語系化字串。
        /// </summary>
        internal static string BA03A_CUR_ID {
            get {
                return ResourceManager.GetString("BA03A_CUR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幣別名稱 的當地語系化字串。
        /// </summary>
        internal static string BA03A_CUR_NM {
            get {
                return ResourceManager.GetString("BA03A_CUR_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設匯率 的當地語系化字串。
        /// </summary>
        internal static string BA03A_CUR_RT {
            get {
                return ResourceManager.GetString("BA03A_CUR_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        internal static string BA04A_TYP {
            get {
                return ResourceManager.GetString("BA04A_TYP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案 的當地語系化字串。
        /// </summary>
        internal static string CaseClose {
            get {
                return ResourceManager.GetString("CaseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已結案 的當地語系化字串。
        /// </summary>
        internal static string CaseClosed {
            get {
                return ResourceManager.GetString("CaseClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案人 的當地語系化字串。
        /// </summary>
        internal static string CloseUser {
            get {
                return ResourceManager.GetString("CloseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認申請 的當地語系化字串。
        /// </summary>
        internal static string ConfirmApply {
            get {
                return ResourceManager.GetString("ConfirmApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認結案 的當地語系化字串。
        /// </summary>
        internal static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期 的當地語系化字串。
        /// </summary>
        internal static string DateRangBeg {
            get {
                return ResourceManager.GetString("DateRangBeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到 的當地語系化字串。
        /// </summary>
        internal static string DateRangEnd {
            get {
                return ResourceManager.GetString("DateRangEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期 的當地語系化字串。
        /// </summary>
        internal static string DT_From {
            get {
                return ResourceManager.GetString("DT_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到 的當地語系化字串。
        /// </summary>
        internal static string DT_To {
            get {
                return ResourceManager.GetString("DT_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購單價 的當地語系化字串。
        /// </summary>
        internal static string EachPrice {
            get {
                return ResourceManager.GetString("EachPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 失敗 的當地語系化字串。
        /// </summary>
        internal static string FailureStr {
            get {
                return ResourceManager.GetString("FailureStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 落後天數 的當地語系化字串。
        /// </summary>
        internal static string FallBackDays {
            get {
                return ResourceManager.GetString("FallBackDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 填寫人 的當地語系化字串。
        /// </summary>
        internal static string FillInUser {
            get {
                return ResourceManager.GetString("FillInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可小於零 的當地語系化字串。
        /// </summary>
        internal static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 你好 的當地語系化字串。
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月 的當地語系化字串。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 月份類別占比 的當地語系化字串。
        /// </summary>
        internal static string MonthTypePurchaseRatio {
            get {
                return ResourceManager.GetString("MonthTypePurchaseRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未全數送達 的當地語系化字串。
        /// </summary>
        internal static string NotAllArrive {
            get {
                return ResourceManager.GetString("NotAllArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未結案 的當地語系化字串。
        /// </summary>
        internal static string NotClosed {
            get {
                return ResourceManager.GetString("NotClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未結案 的當地語系化字串。
        /// </summary>
        internal static string NotConfirm {
            get {
                return ResourceManager.GetString("NotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 缺交數量 的當地語系化字串。
        /// </summary>
        internal static string NotEnoughQT {
            get {
                return ResourceManager.GetString("NotEnoughQT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 按 的當地語系化字串。
        /// </summary>
        internal static string Press {
            get {
                return ResourceManager.GetString("Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購占比 的當地語系化字串。
        /// </summary>
        internal static string PurchaseRatio {
            get {
                return ResourceManager.GetString("PurchaseRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到貨單價 的當地語系化字串。
        /// </summary>
        internal static string ReceiveMY {
            get {
                return ResourceManager.GetString("ReceiveMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 退回 的當地語系化字串。
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註說明 的當地語系化字串。
        /// </summary>
        internal static string REM_MM {
            get {
                return ResourceManager.GetString("REM_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必填 的當地語系化字串。
        /// </summary>
        internal static string RequireErrMsg {
            get {
                return ResourceManager.GetString("RequireErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購數量 的當地語系化字串。
        /// </summary>
        internal static string RP01_PUR_QT {
            get {
                return ResourceManager.GetString("RP01_PUR_QT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示順序 的當地語系化字串。
        /// </summary>
        internal static string SEQ_NO {
            get {
                return ResourceManager.GetString("SEQ_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 稅率 的當地語系化字串。
        /// </summary>
        internal static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購金額 的當地語系化字串。
        /// </summary>
        internal static string TOT_PR {
            get {
                return ResourceManager.GetString("TOT_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        internal static string TR01A_ADD_DR {
            get {
                return ResourceManager.GetString("TR01A_ADD_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商 的當地語系化字串。
        /// </summary>
        internal static string TR01A_BA01A_ID {
            get {
                return ResourceManager.GetString("TR01A_BA01A_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司 的當地語系化字串。
        /// </summary>
        internal static string TR01A_CPN_NM {
            get {
                return ResourceManager.GetString("TR01A_CPN_NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯率 的當地語系化字串。
        /// </summary>
        internal static string TR01A_CUR_RT {
            get {
                return ResourceManager.GetString("TR01A_CUR_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預計交期 的當地語系化字串。
        /// </summary>
        internal static string TR01A_EXP_DT {
            get {
                return ResourceManager.GetString("TR01A_EXP_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票編號 的當地語系化字串。
        /// </summary>
        internal static string TR01A_IVN_NO {
            get {
                return ResourceManager.GetString("TR01A_IVN_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購日期 的當地語系化字串。
        /// </summary>
        internal static string TR01A_PUR_DT {
            get {
                return ResourceManager.GetString("TR01A_PUR_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購單號 的當地語系化字串。
        /// </summary>
        internal static string TR01A_PUR_NO {
            get {
                return ResourceManager.GetString("TR01A_PUR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到貨日期 的當地語系化字串。
        /// </summary>
        internal static string TR01A_RCV_DT {
            get {
                return ResourceManager.GetString("TR01A_RCV_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 價錢 的當地語系化字串。
        /// </summary>
        internal static string TR01B_PUR_PR {
            get {
                return ResourceManager.GetString("TR01B_PUR_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        internal static string TR01B_PUR_QT {
            get {
                return ResourceManager.GetString("TR01B_PUR_QT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 對應資料 的當地語系化字串。
        /// </summary>
        internal static string TR01B_REL_NO {
            get {
                return ResourceManager.GetString("TR01B_REL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 合計 的當地語系化字串。
        /// </summary>
        internal static string TR01B_Sum {
            get {
                return ResourceManager.GetString("TR01B_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購管理 的當地語系化字串。
        /// </summary>
        internal static string TR01M {
            get {
                return ResourceManager.GetString("TR01M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到貨量 的當地語系化字串。
        /// </summary>
        internal static string TR01M_ArriveQT {
            get {
                return ResourceManager.GetString("TR01M_ArriveQT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到貨數量 的當地語系化字串。
        /// </summary>
        internal static string TR01M_ARR_QT {
            get {
                return ResourceManager.GetString("TR01M_ARR_QT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 到貨匯率 的當地語系化字串。
        /// </summary>
        internal static string TR01M_CUR_RT {
            get {
                return ResourceManager.GetString("TR01M_CUR_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票金額 的當地語系化字串。
        /// </summary>
        internal static string TR01M_INV_MY {
            get {
                return ResourceManager.GetString("TR01M_INV_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票號碼 的當地語系化字串。
        /// </summary>
        internal static string TR01M_INV_NO {
            get {
                return ResourceManager.GetString("TR01M_INV_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        internal static string TR01M_Status {
            get {
                return ResourceManager.GetString("TR01M_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發票金額 的當地語系化字串。
        /// </summary>
        internal static string TRM_INV_MY {
            get {
                return ResourceManager.GetString("TRM_INV_MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 採購類別佔比 的當地語系化字串。
        /// </summary>
        internal static string TypePurchaseRatio {
            get {
                return ResourceManager.GetString("TypePurchaseRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        internal static string TYP_ID {
            get {
                return ResourceManager.GetString("TYP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年 的當地語系化字串。
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年度類別占比 的當地語系化字串。
        /// </summary>
        internal static string YearTypePurchaseRatio {
            get {
                return ResourceManager.GetString("YearTypePurchaseRatio", resourceCulture);
            }
        }
    }
}
